baseurl = "https://drifter.fun"
publishDir = "docs"
languageCode = "en-us"
title = "DrifterFun"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = "drifterfun"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "博客"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "文献阅读"
    url = "/paper/"
    weight = 3
[[menu.main]]
    name = "简历"
    url = "/resume/"
    weight = 4
[[menu.main]]
    name = "作品集"
    url = "/works/"
    weight = 5
[[menu.main]]
    name = "留言板"
    url = "/guestbook/guestbook/"
    weight = 6
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 7
[[menu.main]]
    name = "RSS订阅"
    url = "/index.xml/"
    weight = 8


[params]
    description = "One need not hope in order to undertake, nor succeed in order to persevere."
    footer = "&copy; [Drifter Fun](https://drifter.fun) 2018 | [Github](https://github.com/DrifterFun)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
