baseURL = "https://xlmaverick.me"
publishDir = "docs"
languageCode = "en-us"
title = "XLMaverick"
theme = "hugo-lamp"
googleAnalytics = "UA-XXX-X"          # Google Analytics UA number




[params]
  subtitle = "凡心所向 素履所往"
  author = "杨兴隆"
  logo = "/img/avatar.jpg"
  description = "A light responsive Hugo AMP theme for blogger"
  paginate = 10

  # Publisher
  ## adsensePublisher = "ca-pub-XXX"    # Required if you want to include Google Adsense
  adsenseSlot = "XXX"                   # Required slot to display ads
  adsenseSlotSticky = "XXX"             # Enables sticky ads feature, value maybe the same with adsenseSlot, remove if you don't want display sticky ads

  # SEO configs
  seotitle = "XLMverick - garabatear of yang"
  googleSiteVerification = "google_site_verification_code"    # Google Webmaster
  msValidate = "bing_site_verification_code"                  # Bing Webmaster

  # Social networks
  email = "yangxl0319@163.com"
  github = "https://github.com/XLMaverick"
  # twitter = "twitter_username"
  # linkedin = "linkedin_username"
  # facebook = "facebook_username"
  # google = "googleplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # dribbble = "dribbble_username"
  # wechat= "/img/weixinqcode.jpeg"

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = "主页"
  weight = 1
  identifier = "home"
  url = "/home/"
[[menu.main]]
  name = "博客"
  weight = 2
  identifier = "post"
  url = "/post/"
[[menu.main]]
  name = "简历"
  weight = 3
  identifier = "resume"
  url = "/resume/"
  [[menu.main]]
  name = "关于"
  weight = 4
  identifier = "about"
  url = "/about/"
